name: lamsatdawa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_core_web: ^2.19.0
  cloud_firestore: ^5.6.2
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  cloud_firestore_web: ^4.4.2
  cached_network_image:
  intl: ^0.18.0
  another_flutter_splash_screen: ^1.2.1
  lottie: ^3.3.0
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - image/
    - image/LottieLogo2.json
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/Roboto-Regular.ttf
        - asset: assets/Roboto-Bold.ttf
          weight: 700
        - asset: assets/Roboto-Medium.ttf
          weight: 500
        - asset: assets/Roboto-Italic.ttf
          style: italic
    - family: NotoEmoji
      fonts:
        - asset: assets/NotoEmoji-Regular.ttf
